name: Generate Date Image

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  generate_date_image:
    runs-on: ubuntu-latest

    outputs:
      date_image: ${{ steps.generate_date.outputs.date_image }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get install -y imagemagick
          curl -o Roboto-Regular.ttf -L https://github.com/garvit-exe/garvit-exe/raw/main/assets/fonts/Roboto-Regular.ttf

      - name: Generate Date Image
        id: generate_date
        run: |
          DATE=$(date +'%a, %d-%m-%Y')
          convert xc:none -font Roboto-Regular.ttf -pointsize 20 -fill purple -gravity center label:"$DATE" dist/date.png
          echo "::set-output name=date_image::dist/date.png"

      - name: Push date.png to the date branch
        uses: actions/checkout@v2
        with:
          ref: date
