name: Generate Date Image

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at 00:00 UTC

  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  generate_date_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependancies
        run: |
          npm install imagemagick
          curl -o Roboto-Regular.ttf -L https://github.com/garvit-exe/garvit-exe/raw/main/assets/fonts/Roboto-Regular.ttf
        run: |
          DATE=$(date +'%a, %d-%m-%Y')
          convert xc:none -font Roboto-Regular.ttf -pointsize 20 -fill purple -gravity center label:"$DATE" date.png

      - name: Commit changes
        run: |
          git config --local user.email "garvitbudhiraja02@gmail.com"
          git config --local user.name "garvit-exe"
          git add date.png
          git commit -m "Update current date image" || echo "No changes to commit"
          git push
