name: Update Date

on:
  schedule:
    - cron: '30 5 * * *'  # Runs every day at 00:00 IST (05:30 UTC)
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_date:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install --save date-fns

      - name: Generate Date Image
        run: node js/generate_date.js

      - name: Upload Date Image
        uses: actions/upload-artifact@v2
        with:
          name: date
          path: date.png
