name: Update Date

on:
  schedule:
    - cron: '30 5 * * *'  # Runs every day at 00:00 IST (05:30 UTC)
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_date:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Date
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: $(date +'%a, %d-%m-%Y')

      - name: Commit changes
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
